'use client';

import { useMemo, useState } from 'react';
import { ImagePlus } from 'lucide-react';
import { ProductImage } from '@/components/product-image';
import { Input, Label, Select, Textarea } from '@/components/ui';
import { SubmitButton } from '@/components/form-actions';

export function ProductForm({ action, categories, product }: { action: (formData: FormData) => Promise<void>; categories: { id: string; name: string }[]; product?: { id: string; categoryId: string; name: string; slug: string; description: string | null; price: unknown; imageUrl: string | null; available: boolean; active: boolean } }) {
  const [file, setFile] = useState<File | null>(null);
  const previewUrl = useMemo(() => (file ? URL.createObjectURL(file) : product?.imageUrl ?? null), [file, product?.imageUrl]);

  return <form action={action} className="grid gap-4">{product ? <input type="hidden" name="id" value={product.id} /> : null}<div className="grid gap-2"><Label>Category</Label><Select name="categoryId" defaultValue={product?.categoryId ?? ''} required><option value="">Select category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select></div><div className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label>Name</Label><Input name="name" defaultValue={product?.name} required /></div><div className="grid gap-2"><Label>Slug</Label><Input name="slug" defaultValue={product?.slug} required /></div></div><div className="grid gap-2"><Label>Description</Label><Textarea name="description" defaultValue={product?.description ?? ''} /></div><div className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label>Price</Label><Input name="price" type="number" step="0.01" min="0" defaultValue={product ? Number(product.price) : undefined} required /></div><div className="grid gap-2"><Label>Product Image</Label><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm font-medium text-[var(--foreground)]"><ImagePlus className="h-4 w-4" />Upload image<input name="image" type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label><p className="text-xs text-slate-500">Accepted: JPG, PNG, WEBP • Max 5MB</p>{previewUrl ? <div className="mt-2 rounded-2xl border border-[var(--border)] bg-white p-3"><p className="mb-2 text-xs font-medium uppercase tracking-wide text-slate-500">Preview</p><ProductImage src={previewUrl} alt={product?.name ?? 'Product preview'} className="h-40 rounded-xl" sizes="160px" /></div> : null}{product?.imageUrl ? <label className="flex items-center gap-2 text-sm text-slate-600"><input name="removeImage" type="checkbox" /> Remove current image</label> : null}</div></div><div className="flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input name="available" type="checkbox" defaultChecked={product?.available ?? true} /> Available</label><label className="flex items-center gap-2"><input name="active" type="checkbox" defaultChecked={product?.active ?? true} /> Active</label></div><SubmitButton pendingText={product ? 'Updating product...' : 'Saving product...'}>{product ? 'Update Product' : 'Save Product'}</SubmitButton></form>;
}
